#### Task 1: Import libraries

In [1]:
import pandas as pd
import numpy as np
import os

#### Task 2: Open file
Open the file called 'tripadvisor_review.csv' and display the first 10 rows.

In [37]:
file_name = 'tripadvisor_review.csv'
df = pd.read_csv(file_name)
df.head(10)

art galleries  dance clubs  juice bars  restaurants  museums  resorts  \
0           1.80         2.29        0.62         0.80     2.42     3.19   
1           2.20         2.66        0.64         1.42     3.18     3.21   
2           0.80         0.54        0.53         0.24     1.54     3.18   
3           1.80         0.29        0.57         0.46     1.52     3.18   
4           1.20         1.18        0.57         1.54     2.02     3.18   
5           1.28         0.72        0.27         0.74     1.26     3.17   
6           1.36         0.26        0.32         0.86     1.58     3.17   
7           1.40         0.22        0.41         0.82     1.50     3.17   
8           1.76         1.04        0.64         0.82     2.14     3.18   
9           1.36         0.22        0.26         1.50     1.54     3.17   

   parks  beaches  theaters  
0   2.79     1.82      2.42  
1   2.63     1.86      2.32  
2   2.80     1.31      2.50  
3   2.96     1.57      2.86  
4   2.78     1.18      2.54  
5   2.89     1.66      3.66  
6   2.66     1.22      3.22  
7   2.81     1.54      2.88  
8   2.79     1.41      2.54  
9   2.82     2.24      3.12

#### Task 3: Fit 2-cluster model

In [48]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2, random_state=42)
df['cluster'] = kmeans.fit_predict(df)

print("Cluster Centers:\n", kmeans.cluster_centers_)

Cluster Centers:
 [[ 1.30989967e+00  4.91989967e-01  5.00367893e-01  7.86254181e-01
   1.62528428e+00  3.17697324e+00  2.85433110e+00  1.59712375e+00
   2.92548495e+00 -2.10942375e-15 -2.10942375e-15]
 [ 1.41947644e+00  1.82939791e+00  5.82801047e-01  1.18000000e+00
   2.18356021e+00  3.18714660e+00  2.80489529e+00  1.52609948e+00
   2.60157068e+00  1.00000000e+00  1.00000000e+00]]


#### Task 4: Print Centroid Values
Centroid Values for 2-cluster model

In [81]:
for i, center in enumerate(kmeans.cluster_centers_):
    print(f"Centroid {i + 1}: {center}")

Centroid 1: [ 1.30989967e+00  4.91989967e-01  5.00367893e-01  7.86254181e-01
  1.62528428e+00  3.17697324e+00  2.85433110e+00  1.59712375e+00
  2.92548495e+00 -2.10942375e-15 -2.10942375e-15]
Centroid 2: [1.41947644 1.82939791 0.58280105 1.18       2.18356021 3.1871466
 2.80489529 1.52609948 2.60157068 1.         1.        ]


#### Task 5: Print Labels
Print the labels for a subset of the observations

I'm not looking for a specific number of observations here, just don't print all of them because the output gets cumbersome

Expected output:

[0 0 1 1 0 1 1 1 0 1 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 1 0]

I've output 30 labels here; just output at least 5 but less than 30

In [67]:
print(df['cluster'].values[:20])

[1 1 0 0 1 0 0 0 1 0 1 0 1 1 1 1 0 1 1 1]


#### Task 6: Identify the number of observations in each cluster

Expected output:

cluster 0: 382

cluter 1: 598

In [71]:
cluster_counts = df['cluster'].value_counts().sort_index()

for cluster_label, count in cluster_counts.items():
    print(f"cluster {cluster_label}: {count}")

cluster 0: 598
cluster 1: 382


#### Task 7: Calculate Silhouette Score

In [80]:
from sklearn.metrics import silhouette_score

features = df.drop('cluster', axis=1)

score = silhouette_score(features, df['cluster'])

print(f"Silhouette Score: {score:.4f}")


Silhouette Score: 0.4721


#### Task 8: Repeat for a 3-cluster model
Generate a new model using 3 clusters instead of 2

Repeat all of the steps from previous tasks to generate the model and print centroid values, labels, number of observations, and silhouette score.

We will compare the centroid values and silhouette scores to determine which model is a better fit for the data


In [84]:
from sklearn.cluster import KMeans

# Fit KMeans with 3 clusters
kmeans_3 = KMeans(n_clusters=3, random_state=42)
df['cluster_3'] = kmeans_3.fit_predict(df.drop(['cluster'], axis=1))

print("Centroid Values for 3-cluster model:")
for i, center in enumerate(kmeans_3.cluster_centers_):
    print(f"Centroid {i + 1}: {center}")

print("Cluster labels for a subset of the observations:")
print(df['cluster_3'].values[:20])

cluster_counts_3 = df['cluster_3'].value_counts().sort_index()
for label, count in cluster_counts_3.items():
    print(f"cluster {label}: {count}")

from sklearn.metrics import silhouette_score

# Calculate silhouette score (use only features, exclude both label columns)
features = df.drop(['cluster', 'cluster_3'], axis=1)
sil_score_3 = silhouette_score(features, df['cluster_3'])

print(f"Silhouette Score for 3-cluster model: {sil_score_3:.4f}")


Centroid Values for 3-cluster model:
Centroid 1: [ 1.40972112e+00  4.45976096e-01  5.77011952e-01  1.01211155e+00
  2.02167331e+00  3.17836653e+00  2.86733068e+00  1.69390438e+00
  2.81752988e+00  1.66533454e-15 -5.32907052e-15]
Centroid 2: [1.23769452e+00 5.25273775e-01 4.44927954e-01 6.22881844e-01
 1.33855908e+00 3.17596542e+00 2.84492795e+00 1.52711816e+00
 3.00357349e+00 2.16493490e-15 2.00000000e+00]
Centroid 3: [1.41947644 1.82939791 0.58280105 1.18       2.18356021 3.1871466
 2.80489529 1.52609948 2.60157068 1.         1.        ]
Cluster labels for a subset of the observations:
[2 2 1 1 2 1 1 1 2 0 2 0 2 2 2 2 1 2 2 2]
cluster 0: 251
cluster 1: 347
cluster 2: 382
Silhouette Score for 3-cluster model: 0.2320


#### Task 9:

Configure the cell below as a markdown cell and answer the following questions in the cell:

1) Look at the centroids for the 2-cluster model.  List 2 features whose centroid values arevery different. What does this tell you about those features?
2) Look at the centroids for the 2-cluster model.  List 2 features whose centroid values are very similar. What does this tell you about these features?
3) How many values are in  each individual cluster of the 2-cluster model?
4)  Which model, the 2-cluster or the 3-cluster model, is a better fit for the data? How can you tell?



Answers:

1) Two features whose centroid values are very different Dance clubs and Museums. These features show strong differences between clusters and or important in separating user behavior.

2) Two features whose centroid values are very similar were Resorts and Parks.

3) Cluster 0 had 598 values and cluster 1 had 382 values.

4) The 2-cluster model is a better fit for the data because it has a higher silhouette score.
